### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by Fastidious** [alexnguyennz/pagerefresher#1]
Latest Chrome 110 broke the extension. Any chance for an update? Thanks!

**Comment by alexnguyennz** [comment]
Hi it seems ok on my end (110.0.5481.178, Windows 10). Do you mind sharing more info about the issue like your device, and what happens?

**Comment by Fastidious** [comment]
I will gather details tomorrow. The gist is I set the timer, and enable it, and it does nothing. When I look at the settings again it is off. I will try removing and re-adding it again tomorrow, and see how it goes. 

This is under macOS Ventura, on an Intel iMac.

**Comment by Fastidious** [comment]
It seems it is broken (it used to work, but not anymore) on the management interface for GoAnywhere (now Fortra). As I do not have a URL to provide (interface is on intranet), I figure this issue can be closed. Thanks!
