### ISSUE TITLE
Refresh by time

### ISSUE THREAD

**Issue by aleks-ko89** [alexnguyennz/pagerefresher#2]
Can you make a timer by exact time? 
for example, I need it once a day at 12:00

**Comment by alexnguyennz** [comment]
Hi sorry I missed this. Do you mean having a browser tab open and having that reload once a day?

**Comment by aleks-ko89** [comment]
Hi. Yes. Reboot not by contdown, but by time. 
To be honest, I don't need this functionality anymore, but if you're interested in doing it, maybe someone else will find it useful.

**Comment by alexnguyennz** [comment]
All good. Thanks for reaching out.
